openapi: 3.1.0
info:
  title: Public Blog API
  version: 1.0.0
  description: >
    Accès public en lecture aux articles WordPress exposés via REST API. 
    Supporte la récupération de la liste des articles ainsi que l'accès individuel via un ID.
servers:
  - url: https://wordpressa.onrender.com/wp-json/wp/v2
paths:
  /posts:
    get:
      operationId: getPublicPosts
      summary: Récupère les derniers articles du blog
      parameters:
        - name: per_page
          in: query
          description: Nombre d'articles à récupérer (max 100)
          required: false
          schema:
            type: integer
        - name: _fields
          in: query
          description: Champs spécifiques à inclure (ex: title,link)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Liste des articles
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostSummary'
  /posts/{id}:
    get:
      operationId: getPostById
      summary: Récupère un article complet par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Article trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostDetail'

components:
  schemas:
    PostSummary:
      type: object
      properties:
        id:
          type: integer
        title:
          type: object
          properties:
            rendered:
              type: string
        link:
          type: string
    PostDetail:
      type: object
      properties:
        id:
          type: integer
        title:
          type: object
          properties:
            rendered:
              type: string
        content:
          type: object
          properties:
            rendered:
              type: string
        link:
          type: string
