services:
  - type: web
    name: wp-api-backend
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node index.js
envVars:
  - key: WP_USERNAME
    value: "numtema"
  - key: WP_PASSWORD
    value: "lzxaIEgFEIMINjiP2UJsUNuI"
  - key: WP_BASE_URL
    value: "https://numtemaagency.com/wp-json/wp/v2"
