openapi: 3.1.0
info:
  title: Public Blog API
  version: 1.0.0
  description: Accès public aux articles WordPress
servers:
  - url: https://wordpressa.onrender.com/wp-json/wp/v2
paths:
  /posts:
    get:
      operationId: getPublicPosts
      summary: Récupère les derniers articles du blog
      parameters:
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
        - name: _fields
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Liste des articles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: object
                      properties:
                        rendered:
                          type: string
                    link:
                      type: string
